development:
  adapter: mysql
  database: gratitudes_develpoment
  host: localhost
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: gratitudes_test
  host: localhost
  username: root
  password: 
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  database: b7phgnqf87tv9670
  host: b7phgnqf87tv9670.mysql.clvrcld.net
  username: uopjbeuovcgjaa72
  password: 50c7d4103791463c9c9325365973646f
  pool: 5
  timeout: 5000
